name: ReVanced Music

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 

      - name: Download YouTube APK
        uses: robinraju/release-downloader@v1.8
        with:
          repository: '${{ github.repository }}'
          tag: base
          fileName: youtube.apk
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Build APKs
        run: ./scripts/build.sh -r

      - name: Set current date as env variable
        run: >-
          echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo
          "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: kevin-david/zipalign-sign-android-release@v1.1.1
        name: Sign ReVanced APK
        id: sign_yt
        with:
          releaseDirectory: build/yt/
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
          zipAlign: true

      - name: Generate SHA256 checksums for the signed APK file
        run: ./scripts/sha256gen.sh -r

      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ env.date_now_nodashes }}-yt'
          title: 'ReVanced Music ${{ env.date_now }}'
          prerelease: false
          files: |
            build/hashes/sha256-yt.txt
            ${{ steps.sign_yt.outputs.signedReleaseFile }}

      - name: Get hashes
        id: hashes
        run: echo "yt=$(cat build/hashes/sha256-yt.txt)" >> $GITHUB_OUTPUT

      - name: Write hashes
        uses: DamianReeves/write-file-action@master
        with:
          path: hashes/yt.txt
          write-mode: overwrite
          contents: |
            ${{ steps.hashes.outputs.yt }}

      - name: Push updated hashes
        uses: Andro999b/push@v1.3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
          force: false
          message: 'revanced-repo: Update hashes'
